### ISSUE TITLE
API group intermittent failures

### ISSUE THREAD

**Issue by gary1998** [ComplianceAsCode/compliance-operator#339]
Hi folks, we're using OpenShift Compliance Operator to carry out scans via the REST APIs and we found out that sometimes it responds with something like followed:
```json
{
	"apiVersion": "v1",
	"code": 403,
	"details": {
		"group": "compliance.openshift.io",
		"kind": "tailoredprofiles"
	},
	"kind": "Status",
	"message": "tailoredprofiles.compliance.openshift.io is forbidden: User \"system:anonymous\" cannot create resource \"tailoredprofiles\" in API group \"compliance.openshift.io\" in the namespace \"openshift-compliance\"",
	"metadata": {},
	"reason": "Forbidden",
	"status": "Failure"
}
```

This happens in almost all CRD operations of the TailoredProfile, ScanSetting, and ScanSettingBinding.

And as I told, it's intermittent. Sometimes it works without any fix and sometimes it doesn't.

**Comment by jhrozek** [comment]
yes, anonymous users are not permitted to create CRDs. You need to log in before creating the resources.

Since the issue is happening intermittently, I would guess that the OAuth timeout might come into play.

This is not an issue in CO and it's not CO that's throwing the error, but the API server.
